apiVersion: v1
kind: Secret
metadata:
  name: dockerlogin
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJyb2hpdGgzNjkiLCJwYXNzd29yZCI6IkRvY2tlckA5IiwiZW1haWwiOiJyb2hpdGhjaG93ZGFyeXZhbGxhYmhhbmVuaUBnbWFpbC5jb20iLCJhdXRoIjoiY205b2FYUm9Nelk1T2tSdlkydGxja0E1In19fQ==

