apiVersion: v1
kind: Service
metadata:
  name: javaapp-nodeport
  labels:
    app: javaapp
  namespace: dev
spec:
  type: NodePort
  ports:
    - nodePort: 31234
      port: 9090
      targetPort: 9090
      protocol: TCP
      name: web
  selector:
    app: javaapp